print("Please input your first value ")
first_number = float(input())
print("Please input your second value ")
second_number = float(input())
print("Please input your third value ")
third_number = float(input())
print("Please input your fourth value ")
fourth_number = float(input())
print("Please input your fifth value ")
fifth_number = float(input())
total_sum = round(first_number + second_number + third_number + fourth_number + fifth_number, 2)
print(total_sum)
