print("Please input an integer number ")
integer_number = int(input())
print("Please input a float number ")
float_number = float(input())
print("Please input a text ")
text = input()
print(text)
print(float_number)
print(integer_number)